---
- name: All Server 
  hosts: all
  become: yes
  roles:
    - role: docker
      version: 18.06.3~ce~3-0~ubuntu
    - role: k8s-common
      version: 1.18.0-00
      ip: "{{ ansible_host }}"

- name: Master Server
  hosts: master
  become: yes
  roles:
  - role: k8s-master
    version: 1.18.0-00
    cidr: 10.244.0.0/16
    ip: "{{ hostvars['k8s-master']['ansible_host'] }}"
    user: "{{ hostvars['k8s-master']['ansible_user'] }}"
    k8s_middle_server: k8s_middle_server

- name: Worker Servers
  gather_facts: yes
  hosts: workers
  become: yes
  roles:
  - role: k8s-worker
    version: 1.18.0-00
    k8s_middle_server: k8s_middle_server

